# Generated by Django 4.1.3 on 2022-12-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('Dep', models.CharField(max_length=200)),
                ('Dr', models.CharField(max_length=200)),
                ('cname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('cdate', models.CharField(max_length=20)),
                ('ctime', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=10)),
            ],
        ),
    ]
