# Generated by Django 4.1.3 on 2022-12-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField(max_length=200)),
                ('doc', models.CharField(max_length=200)),
                ('hname', models.CharField(max_length=20)),
                ('m1', models.CharField(max_length=20)),
                ('hdate', models.CharField(max_length=20)),
                ('t1', models.CharField(max_length=200)),
                ('a1', models.CharField(max_length=10)),
            ],
        ),
    ]
