# Generated by Django 4.1.3 on 2022-12-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_a1_appointment_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointment',
        ),
    ]
